include: package:very_good_analysis/analysis_options.3.0.2.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'
